#!/bin/bash
#
# $Header: /home/cvs/webCal/webCal2/wcald-redhat,v 1.2 2003/06/27 20:09:04 mzou Exp $
#

#
# wcald 	This shell script takes care of starting and stopping
#                 wcald (The email daemon for web calender)
#
# Author:   Dirk Elmendorf <dirk@rackspace.com>
#           slightly modified by mzou@mail.ma.utexas.edu
#
# chkconfig: - 55 45
# description: The email reminder daemon \
# that sends out emails from web calender
# probe: true

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "${NETWORKING}" = "no" ] && exit 0


[ -f /var/www/webcal/bin/wcald ] || exit 0


RETVAL=0
prog="wcald"


start() {
	echo -n $"Starting $prog: "
	daemon /var/www/webcal/bin/wcald
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/wcald
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc /var/www/webcal/bin/wcald
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/wcald
	return $RETVAL
}	


restart() {
  	stop
	start
}	


case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|reload}"
	exit 1
esac

exit $?
